# Generated by Django 5.2.9 on 2025-12-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview', models.TextField(blank=True, help_text='Short preview text', null=True)),
                ('content', models.TextField(blank=True, help_text='Full content text', null=True)),
                ('date', models.DateField()),
                ('order', models.IntegerField(default=0, help_text='Order within chapter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main_period', 'Main Timeline Period'), ('branch', 'Branch (e.g., Career, Relationships)'), ('branch_period', 'Branch Period')], default='main_period', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('x_position', models.IntegerField(default=0, help_text='X position for branches')),
                ('collapsed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order within same type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_branch', models.ForeignKey(blank=True, help_text='For branch periods, link to parent branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='myapp.chapter')),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
