# Generated by Django 5.2.9 on 2025-12-19 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.JSONField(default={}, help_text='Title, description, and any other sensitive data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Indicates if content is encrypted'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Indicates if content is encrypted'),
        ),
        migrations.AlterField(
            model_name='event',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='myapp.chapter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.JSONField(default={}, help_text='Title, preview, description, and full content'),
            preserve_default=False,
        ),
    ]
