# Generated by Django 5.2.9 on 2025-12-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_chapter_description_remove_chapter_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.JSONField(default=dict, help_text='Title, description, and other sensitive data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.JSONField(default=dict, help_text='Title, preview, description, full content'),
        ),
    ]
