# Generated by Django 5.2.9 on 2025-12-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_chapter_content_alter_event_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.JSONField(default=dict, help_text='Title, description, etc.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.JSONField(default=dict, help_text='Title, description, etc.'),
        ),
    ]
