# Generated by Django 5.2.9 on 2025-12-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chapter_content_alter_event_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='myapp.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
