# Generated by Django 5.2.9 on 2025-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_chapter_content_alter_chapter_is_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='is_encrypted',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_encrypted',
        ),
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='tester', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='tester', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='type',
            field=models.CharField(choices=[('main_period', 'Main Period'), ('branch', 'Branch'), ('branch_period', 'Branch Period')], default='main_period', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
