# Generated by Django 5.2.9 on 2025-12-25 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_chapter_content_remove_chapter_is_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='source_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_branches', to='myapp.chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='source_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_branches', to='myapp.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'branch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_entries', to='myapp.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parent_branch',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'branch'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='myapp.chapter'),
        ),
    ]
