# Generated by Django 5.2.9 on 2025-12-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_chapter_source_chapter_chapter_source_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='source_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_spawned_branches', to='myapp.chapter'),
        ),
    ]
